//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalamancaWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControllerNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalamancaWeb.Resources.ControllerNames", typeof(ControllerNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedent.
        /// </summary>
        public static string Antecedent {
            get {
                return ResourceManager.GetString("Antecedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AntecedentType.
        /// </summary>
        public static string AntecedentType {
            get {
                return ResourceManager.GetString("AntecedentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttentionStatus.
        /// </summary>
        public static string AttentionStatus {
            get {
                return ResourceManager.GetString("AttentionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiseaseType.
        /// </summary>
        public static string DiseaseType {
            get {
                return ResourceManager.GetString("DiseaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentIdentityType.
        /// </summary>
        public static string DocumentIdentityType {
            get {
                return ResourceManager.GetString("DocumentIdentityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquery.
        /// </summary>
        public static string Inquery {
            get {
                return ResourceManager.GetString("Inquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginUser.
        /// </summary>
        public static string LoginUser {
            get {
                return ResourceManager.GetString("LoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuffersFrom.
        /// </summary>
        public static string SuffersFrom {
            get {
                return ResourceManager.GetString("SuffersFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment.
        /// </summary>
        public static string Treatment {
            get {
                return ResourceManager.GetString("Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreatmentDetail.
        /// </summary>
        public static string TreatmentDetail {
            get {
                return ResourceManager.GetString("TreatmentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreatmentEvolution.
        /// </summary>
        public static string TreatmentEvolution {
            get {
                return ResourceManager.GetString("TreatmentEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreatmentStatus.
        /// </summary>
        public static string TreatmentStatus {
            get {
                return ResourceManager.GetString("TreatmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreatmentType.
        /// </summary>
        public static string TreatmentType {
            get {
                return ResourceManager.GetString("TreatmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserType.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
    }
}
