//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalamancaWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalamancaWeb.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Antecedente.
        /// </summary>
        public static string ERROR_ADD_ANTECEDENT {
            get {
                return ResourceManager.GetString("ERROR_ADD_ANTECEDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tipo de Antecedente.
        /// </summary>
        public static string ERROR_ADD_ANTECEDENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ADD_ANTECEDENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar la Cita.
        /// </summary>
        public static string ERROR_ADD_APPOINTMENT {
            get {
                return ResourceManager.GetString("ERROR_ADD_APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tratamiento de la Cita.
        /// </summary>
        public static string ERROR_ADD_APPOINTMENT_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_ADD_APPOINTMENT_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tipo de Estado de Atencion.
        /// </summary>
        public static string ERROR_ADD_ATTENTION_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ADD_ATTENTION_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Departamento.
        /// </summary>
        public static string ERROR_ADD_CITY {
            get {
                return ResourceManager.GetString("ERROR_ADD_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Pais.
        /// </summary>
        public static string ERROR_ADD_COUNTRY {
            get {
                return ResourceManager.GetString("ERROR_ADD_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tipo de Padecimiento.
        /// </summary>
        public static string ERROR_ADD_DISEASE_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ADD_DISEASE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tipo de Documento de Identidad.
        /// </summary>
        public static string ERROR_ADD_DOCUMENT_IDENTITY_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ADD_DOCUMENT_IDENTITY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar Sexo.
        /// </summary>
        public static string ERROR_ADD_GENDER {
            get {
                return ResourceManager.GetString("ERROR_ADD_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar la Consulta.
        /// </summary>
        public static string ERROR_ADD_INQUERY {
            get {
                return ResourceManager.GetString("ERROR_ADD_INQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar la Persona.
        /// </summary>
        public static string ERROR_ADD_PERSON {
            get {
                return ResourceManager.GetString("ERROR_ADD_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Padecimiento.
        /// </summary>
        public static string ERROR_ADD_SUFFERS_FROM {
            get {
                return ResourceManager.GetString("ERROR_ADD_SUFFERS_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tratamiento.
        /// </summary>
        public static string ERROR_ADD_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_ADD_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Detalle del Tratamiento.
        /// </summary>
        public static string ERROR_ADD_TREATMENT_DETAIL {
            get {
                return ResourceManager.GetString("ERROR_ADD_TREATMENT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar la Evolucion del Tratamiento.
        /// </summary>
        public static string ERROR_ADD_TREATMENT_EVOLUTION {
            get {
                return ResourceManager.GetString("ERROR_ADD_TREATMENT_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tipo de Estado de Tratameinto.
        /// </summary>
        public static string ERROR_ADD_TREATMENT_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ADD_TREATMENT_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tipo de Tratamiento.
        /// </summary>
        public static string ERROR_ADD_TREATMENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ADD_TREATMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Usuario.
        /// </summary>
        public static string ERROR_ADD_USER {
            get {
                return ResourceManager.GetString("ERROR_ADD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al agregar el Tipo de Usuario.
        /// </summary>
        public static string ERROR_ADD_USER_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ADD_USER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Antecedente.
        /// </summary>
        public static string ERROR_DELETE_ANTECEDENT {
            get {
                return ResourceManager.GetString("ERROR_DELETE_ANTECEDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tipo de Antecedente.
        /// </summary>
        public static string ERROR_DELETE_ANTECEDENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_DELETE_ANTECEDENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar la Cita.
        /// </summary>
        public static string ERROR_DELETE_APPOINTMENT {
            get {
                return ResourceManager.GetString("ERROR_DELETE_APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tratamiento de la Cita.
        /// </summary>
        public static string ERROR_DELETE_APPOINTMENT_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_DELETE_APPOINTMENT_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tipo de Estado de Atencion.
        /// </summary>
        public static string ERROR_DELETE_ATTENTION_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_DELETE_ATTENTION_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Departamento.
        /// </summary>
        public static string ERROR_DELETE_CITY {
            get {
                return ResourceManager.GetString("ERROR_DELETE_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Pais.
        /// </summary>
        public static string ERROR_DELETE_COUNTRY {
            get {
                return ResourceManager.GetString("ERROR_DELETE_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tipo de Padecimiento.
        /// </summary>
        public static string ERROR_DELETE_DISEASE_TYPE {
            get {
                return ResourceManager.GetString("ERROR_DELETE_DISEASE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tipo de Documento de Identidad.
        /// </summary>
        public static string ERROR_DELETE_DOCUMENT_IDENTITY_TYPE {
            get {
                return ResourceManager.GetString("ERROR_DELETE_DOCUMENT_IDENTITY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Sexo.
        /// </summary>
        public static string ERROR_DELETE_GENDER {
            get {
                return ResourceManager.GetString("ERROR_DELETE_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar la Consulta.
        /// </summary>
        public static string ERROR_DELETE_INQUERY {
            get {
                return ResourceManager.GetString("ERROR_DELETE_INQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar la Persona.
        /// </summary>
        public static string ERROR_DELETE_PERSON {
            get {
                return ResourceManager.GetString("ERROR_DELETE_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Padecimiento.
        /// </summary>
        public static string ERROR_DELETE_SUFFERS_FROM {
            get {
                return ResourceManager.GetString("ERROR_DELETE_SUFFERS_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tratamiento.
        /// </summary>
        public static string ERROR_DELETE_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_DELETE_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Detalle del Tratamiento.
        /// </summary>
        public static string ERROR_DELETE_TREATMENT_DETAIL {
            get {
                return ResourceManager.GetString("ERROR_DELETE_TREATMENT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar la Evolucion del Tratamiento.
        /// </summary>
        public static string ERROR_DELETE_TREATMENT_EVOLUTION {
            get {
                return ResourceManager.GetString("ERROR_DELETE_TREATMENT_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tipo de Estado de Tratameinto.
        /// </summary>
        public static string ERROR_DELETE_TREATMENT_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_DELETE_TREATMENT_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tipo de Tratamiento.
        /// </summary>
        public static string ERROR_DELETE_TREATMENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_DELETE_TREATMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Usuario.
        /// </summary>
        public static string ERROR_DELETE_USER {
            get {
                return ResourceManager.GetString("ERROR_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el Tipo de Usuario.
        /// </summary>
        public static string ERROR_DELETE_USER_TYPE {
            get {
                return ResourceManager.GetString("ERROR_DELETE_USER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Antecedentes.
        /// </summary>
        public static string ERROR_GET_ANTECEDENT {
            get {
                return ResourceManager.GetString("ERROR_GET_ANTECEDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tipos de Antecedentes.
        /// </summary>
        public static string ERROR_GET_ANTECEDENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_GET_ANTECEDENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener las Citas.
        /// </summary>
        public static string ERROR_GET_APPOINTMENT {
            get {
                return ResourceManager.GetString("ERROR_GET_APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tratamientos de las Citas.
        /// </summary>
        public static string ERROR_GET_APPOINTMENT_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_GET_APPOINTMENT_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tipos de Estados de Atenciones.
        /// </summary>
        public static string ERROR_GET_ATTENTION_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_GET_ATTENTION_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Departamentos.
        /// </summary>
        public static string ERROR_GET_CITY {
            get {
                return ResourceManager.GetString("ERROR_GET_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Paises.
        /// </summary>
        public static string ERROR_GET_COUNTRY {
            get {
                return ResourceManager.GetString("ERROR_GET_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tipos de Padecimientos.
        /// </summary>
        public static string ERROR_GET_DISEASE_TYPE {
            get {
                return ResourceManager.GetString("ERROR_GET_DISEASE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tipos de Documentos de Identidad.
        /// </summary>
        public static string ERROR_GET_DOCUMENT_IDENTITY_TYPE {
            get {
                return ResourceManager.GetString("ERROR_GET_DOCUMENT_IDENTITY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Sexos.
        /// </summary>
        public static string ERROR_GET_GENDER {
            get {
                return ResourceManager.GetString("ERROR_GET_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener las Consultas.
        /// </summary>
        public static string ERROR_GET_INQUERY {
            get {
                return ResourceManager.GetString("ERROR_GET_INQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener las Personas.
        /// </summary>
        public static string ERROR_GET_PERSON {
            get {
                return ResourceManager.GetString("ERROR_GET_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Padecimientos.
        /// </summary>
        public static string ERROR_GET_SUFFERS_FROM {
            get {
                return ResourceManager.GetString("ERROR_GET_SUFFERS_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tratamientos.
        /// </summary>
        public static string ERROR_GET_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_GET_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Detalles de Tratamientos.
        /// </summary>
        public static string ERROR_GET_TREATMENT_DETAIL {
            get {
                return ResourceManager.GetString("ERROR_GET_TREATMENT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener las Evoluciones de Tratamientos.
        /// </summary>
        public static string ERROR_GET_TREATMENT_EVOLUTION {
            get {
                return ResourceManager.GetString("ERROR_GET_TREATMENT_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tipo de Estados de Tratamientos.
        /// </summary>
        public static string ERROR_GET_TREATMENT_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_GET_TREATMENT_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tipos de Tratamientos.
        /// </summary>
        public static string ERROR_GET_TREATMENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_GET_TREATMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Usuarios.
        /// </summary>
        public static string ERROR_GET_USER {
            get {
                return ResourceManager.GetString("ERROR_GET_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Tipos de Usuarios.
        /// </summary>
        public static string ERROR_GET_USER_TYPE {
            get {
                return ResourceManager.GetString("ERROR_GET_USER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Antecedente.
        /// </summary>
        public static string ERROR_SEARCH_ANTECEDENT {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_ANTECEDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tipo de Antecedente.
        /// </summary>
        public static string ERROR_SEARCH_ANTECEDENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_ANTECEDENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar la Cita.
        /// </summary>
        public static string ERROR_SEARCH_APPOINTMENT {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tratamiento de la Cita.
        /// </summary>
        public static string ERROR_SEARCH_APPOINTMENT_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_APPOINTMENT_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tipo de Estado de Atencion.
        /// </summary>
        public static string ERROR_SEARCH_ATTENTION_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_ATTENTION_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Departamento.
        /// </summary>
        public static string ERROR_SEARCH_CITY {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Pais.
        /// </summary>
        public static string ERROR_SEARCH_COUNTRY {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tipo de Padecimiento.
        /// </summary>
        public static string ERROR_SEARCH_DISEASE_TYPE {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_DISEASE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tipo de Documento de Identidad.
        /// </summary>
        public static string ERROR_SEARCH_DOCUMENT_IDENTITY_TYPE {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_DOCUMENT_IDENTITY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Sexo.
        /// </summary>
        public static string ERROR_SEARCH_GENDER {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar la Consulta.
        /// </summary>
        public static string ERROR_SEARCH_INQUERY {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_INQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar la Persona.
        /// </summary>
        public static string ERROR_SEARCH_PERSON {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Padecimiento.
        /// </summary>
        public static string ERROR_SEARCH_SUFFERS_FROM {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_SUFFERS_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tratamiento.
        /// </summary>
        public static string ERROR_SEARCH_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Detalle del Tratamiento.
        /// </summary>
        public static string ERROR_SEARCH_TREATMENT_DETAIL {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_TREATMENT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar la Evolucion del Tratamiento.
        /// </summary>
        public static string ERROR_SEARCH_TREATMENT_EVOLUTION {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_TREATMENT_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tipo de Estado de Tratameinto.
        /// </summary>
        public static string ERROR_SEARCH_TREATMENT_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_TREATMENT_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tipo de Tratamiento.
        /// </summary>
        public static string ERROR_SEARCH_TREATMENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_TREATMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Usuario.
        /// </summary>
        public static string ERROR_SEARCH_USER {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al buscar el Tipo de Usuario.
        /// </summary>
        public static string ERROR_SEARCH_USER_TYPE {
            get {
                return ResourceManager.GetString("ERROR_SEARCH_USER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Antecedente.
        /// </summary>
        public static string ERROR_UPDATE_ANTECEDENT {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_ANTECEDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tipo de Antecedente.
        /// </summary>
        public static string ERROR_UPDATE_ANTECEDENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_ANTECEDENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la Cita.
        /// </summary>
        public static string ERROR_UPDATE_APPOINTMENT {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_APPOINTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tratamiento de la Cita.
        /// </summary>
        public static string ERROR_UPDATE_APPOINTMENT_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_APPOINTMENT_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tipo de Estado de Atencion.
        /// </summary>
        public static string ERROR_UPDATE_ATTENTION_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_ATTENTION_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Departamento.
        /// </summary>
        public static string ERROR_UPDATE_CITY {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Pais.
        /// </summary>
        public static string ERROR_UPDATE_COUNTRY {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tipo de Padecimiento.
        /// </summary>
        public static string ERROR_UPDATE_DISEASE_TYPE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_DISEASE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tipo de Documento de Identidad.
        /// </summary>
        public static string ERROR_UPDATE_DOCUMENT_IDENTITY_TYPE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_DOCUMENT_IDENTITY_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Sexo.
        /// </summary>
        public static string ERROR_UPDATE_GENDER {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la Consulta.
        /// </summary>
        public static string ERROR_UPDATE_INQUERY {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_INQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la Persona.
        /// </summary>
        public static string ERROR_UPDATE_PERSON {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Padecimiento.
        /// </summary>
        public static string ERROR_UPDATE_SUFFERS_FROM {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_SUFFERS_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tratamiento.
        /// </summary>
        public static string ERROR_UPDATE_TREATMENT {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TREATMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Detalle del Tratamiento.
        /// </summary>
        public static string ERROR_UPDATE_TREATMENT_DETAIL {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TREATMENT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar la Evolucion del Tratamiento.
        /// </summary>
        public static string ERROR_UPDATE_TREATMENT_EVOLUTION {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TREATMENT_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tipo de Estado de Tratameinto.
        /// </summary>
        public static string ERROR_UPDATE_TREATMENT_STATUS_TYPE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TREATMENT_STATUS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tipo de Tratamiento.
        /// </summary>
        public static string ERROR_UPDATE_TREATMENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_TREATMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Usuario.
        /// </summary>
        public static string ERROR_UPDATE_USER {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al actualizar el Tipo de Usuario.
        /// </summary>
        public static string ERROR_UPDATE_USER_TYPE {
            get {
                return ResourceManager.GetString("ERROR_UPDATE_USER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No hay Servidor Disponible.
        /// </summary>
        public static string NoServer {
            get {
                return ResourceManager.GetString("NoServer", resourceCulture);
            }
        }
    }
}
